import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
// import AppShell from "@/components/site/AppShell";
import LanguageProvider from "@/i18n/LanguageProvider"; 
import { ThemeProvider } from "@/components/site/ThemeProvider";
import ConditionalLayout from "../components/ConditionalLayout";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });
const notoThai = localFont({
  src: "../../public/fonts/Noto_Sans_Thai/NotoSansThai-VariableFont_wdth,wght.ttf",
  variable: "--font-noto-thai",
  weight: "100 900",
  display: "swap",
});

export const metadata: Metadata = {
  title: "PostHub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${notoThai.variable} antialiased`}>
        <ThemeProvider>
          <LanguageProvider>
            <ConditionalLayout>{children}</ConditionalLayout>
          </LanguageProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
